query pageQuery {
  ...LayoutQueryFragment
  postConnection(sort: "date", first: 1000, last: 1) {
    edges {
      node {
        id
        _values
        _sys {
          filename
        }
      }
    }
  }
}

query contentQuery($relativePath: String!) {
  ...LayoutQueryFragment
  page(relativePath: $relativePath) {
    ...PageParts
  }
}

query blogPostQuery($relativePath: String!) {
  ...LayoutQueryFragment
  post(relativePath: $relativePath) {
    ...PostParts
  }
}
